apiVersion: v1
kind: ConfigMap
metadata:
  name: order-history-app-config
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $val := .Values.configMaps.appConfig }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
