apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docker-nodejs-application.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "docker-nodejs-application.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "docker-nodejs-application.name" . }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ include "docker-nodejs-application.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
